orbs:
  gcp-gcr: circleci/gcp-gcr@0.8.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: app
          registry-url: gcr.io
          extra_build_args: --build-arg E=${ETHERSCAN_KEY} --build-arg A=${API_ENDPOINT} --build-arg R=${127.0.0.1}

          
